import './style.css'

document.addEventListener('DOMContentLoaded', async () => {
    try {
        const response = await fetch('./outputs/results_summary.json');
        const data = await response.json();
        
        renderKPIs(data);
        renderVisuals();
    } catch (err) {
        console.error("Failed to load pipeline data:", err);
        document.getElementById('kpiGrid').innerHTML = `<p style="color:red; grid-column: span 4;">Error loading data. Make sure 'npm run dev' is running and 'outputs' folder is copied to 'public/outputs'.</p>`;
    }
});

function renderKPIs(data) {
    const kpiGrid = document.getElementById('kpiGrid');
    
    // Select the best metrics to highlight the "10x iteration improvement"
    const kpis = [
        { title: "Iterative RMSE", value: data.reconstruction?.rmse?.toFixed(2) || "N/A", sub: `Out-of-sample`, type: 'good' },
        { title: "ADMM Converged Iterations", value: data.admm?.iterations || "N/A", sub: `Adaptive ρ-scaling enabled`, type: 'info' },
        { title: "Anomaly Isolations", value: data.anomalies?.n_detected || 0, sub: `BH-FDR Corrected`, type: 'info' },
        { title: "Flash Crashes Detected", value: data.anomaly_classification?.flash_crash || 0, sub: `Classification Engine`, type: 'crit' },
        { title: "Granger Causal Links", value: data.granger_network?.n_edges || 0, sub: `F-tests across ${data.granger_network?.n_nodes} nodes`, type: 'good' },
        { title: "Kronecker Approx Error", value: `${((data.kronecker_covariance?.approx_error || 0) * 100).toFixed(4)}%`, sub: `Σ ≈ A ⊗ B Fit`, type: 'good' },
    ];

    let html = '';
    kpis.forEach((kpi, idx) => {
        let subClass = kpi.type === 'crit' ? 'critical' : '';
        html += `
            <div class="glass-card" style="animation-delay: ${idx * 0.1}s">
                <div class="kpi-title">${kpi.title}</div>
                <div class="kpi-value">${kpi.value}</div>
                <div class="kpi-sub ${subClass}">${kpi.sub}</div>
            </div>
        `;
    });
    kpiGrid.innerHTML = html;
}

function renderVisuals() {
    const visualsGrid = document.getElementById('visualsGrid');
    
    // Hardcoded layout mapping exactly to the 14 outputs generated by demo.py
    const images = [
        { file: 'cumulative_pnl.png', title: 'Cumulative PnL Simulation', span: 'span-full' },
        { file: 'multi_asset_reconstruction.png', title: 'Multi-Asset Hankel Reconstruction', span: 'span-half' },
        { file: 'forecast_comparison.png', title: 'DMD Forecast Comparison', span: 'span-half' },
        { file: 'reconstruction_comparison.png', title: 'Single Asset Reconstruction Detail', span: 'span-half' },
        { file: 'admm_convergence.png', title: 'ADMM-RPCA Convergence', span: 'span-half' },
        { file: 'granger_network.png', title: 'Granger Causality Network', span: 'span-half' },
        { file: 'anomaly_heatmap.png', title: 'Sparse Anomaly Heatmap', span: 'span-half' },
        { file: 'kronecker_spectrum.png', title: 'Kronecker Covariance Factor Spectrum', span: 'span-half' },
        { file: 'qq_residuals.png', title: 'Residual Q-Q Diagnostic', span: 'span-third' },
        { file: 'dmd_spectrum.png', title: 'DMD Eigenvalue Spectrum', span: 'span-third' },
        { file: 'portfolio_weights.png', title: 'Optimal Portfolio Weights', span: 'span-third' },
        { file: 'backtest_rmse.png', title: 'Rolling Out-of-Sample RMSE', span: 'span-half' },
        { file: 'spectral_density.png', title: 'Power Spectral Density', span: 'span-half' }
    ];

    let html = '';
    images.forEach((img, idx) => {
        html += `
            <div class="img-card ${img.span}" style="animation-delay: ${(idx % 5) * 0.15 + 0.5}s">
                <div class="img-header">${img.title}</div>
                <div class="img-container">
                    <img src="./outputs/${img.file}" alt="${img.title}" loading="lazy"/>
                </div>
            </div>
        `;
    });
    visualsGrid.innerHTML = html;
}
